// <auto-generated />
using System;
using ChatServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace ChatServer.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ChatServer.Models.Message", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsBroadcast")
                    .HasColumnType("INTEGER");

                b.Property<string>("ReceiverId")
                    .HasColumnType("TEXT");

                b.Property<string>("SenderId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Messages");
            });
#pragma warning restore 612, 618
        }
    }
}